services:
  backend:
    build: ./backend
    container_name: flask_api_tp4
    depends_on:
      db:
        condition: service_healthy # Asegura que el contenedor de la base de datos esté saludable antes de iniciar el backend
    env_file:
      - ./.env
    ports:
      - 5002:5000
    volumes:
      - ./backend:/app
    networks:
      - pwd_network
    restart: unless-stopped # Reinicia el contenedor automáticamente a menos que se detenga manualmente
  db:
    image: postgres:15
    container_name: postgres15_tp4
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pwd_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  pwd_network:
    driver: bridge
